### ISSUE TITLE
Clean up branches, merge something to master.

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polygit#4]
It's unclear right now what the canonical code is. It appears to be the review2 branch.

**Comment by garlicnation** [comment]
@justinfagnani https://github.com/Polymer/polygit/tree/branchTagErrorReporting reflects the code running in prod AFAIK.

**Comment by justinfagnani** [comment]
Thanks AJ!

**Comment by heruan** [comment]
Definitely unclear. Also a README would be useful, to know how to run an instance locally (tried compiling with `tsc`, but got errors).

**Comment by heruan** [comment]
Problem was compiling with latest TypeScript version, got it (somewhat) running with:

```shell
$ echo "foo-bar-github-api-key" > /tmp/github_apikey.txt
$ yarn install
$ ./node_modules/typescript/bin/tsc -p tsconfig.json
$ node lib/bin/polygit.js
```
Note: needs NodeJS v6 and a running memcached with large enough memory limits (e.g. `memcached -m 256 -I 128m`.

**Comment by keanulee** [comment]
All branches mentioned above are in `master` which is the currently deployed version. Note that when deployed the GitHub token is retrieved internally:

https://github.com/Polymer/polygit/blob/ca5057b021f9fca078c604b705df46d3f2e8b421/src/bin/polygit.ts#L65-L73
